apiVersion: apps/v1
kind: Deployment
metadata:
  name: point-db
  labels:
    app: point-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: point-db
  template:
    metadata:
      labels:
        app: point-db
    spec:
      hostname: point-db
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_ROOT_PASSWORD
            value: "password"
          - name: MYSQL_DATABASE
            value: "sample"
